
name: build-prerelease

on:
  workflow_dispatch:
  
jobs:
  
  build-Linux:
    runs-on: ubuntu-20.04 
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8

      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r requirements.txt
          
      - name: Build
        run: python3 build.py --build_exe
        
      - name: copy backend
        run: | 
          mv dist/ bin/
          cp -r backend bin/
          
      
      - name: compress archive
        run: |
          zip -r REAL-Video-Enhancer-2.0-Linux.zip bin/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: REAL-Video-Enhancer-2.0-Linux.zip
          path: REAL-Video-Enhancer-2.0-Linux.zip
          
  build-Windows:
    runs-on: windows-2019
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build
        run: python3 build.py --build_exe
        
      - name: copy backend
        run: cp -r backend dist/main/
      
      - name: compress archive
        run: |
            cd dist
            tar -a -c -f REAL-Video-Enhancer-2.0-Windows.zip main
            cd ..
            cp dist/REAL-Video-Enhancer-2.0-Windows.zip REAL-Video-Enhancer-2.0-Windows.zip

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: REAL-Video-Enhancer-2.0-Windows.zip
          path: REAL-Video-Enhancer-2.0-Windows.zip
          
  build-MacOS:
    runs-on: macos-12
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8

      - name: Install Python Dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build
        run: python3 build.py --build_exe
        
      - name: copy backend
        run: cp -r backend dist/
      
      - name: compress archive
        run: zip -r REAL-Video-Enhancer-2.0-MacOS_x86_64.zip dist/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: REAL-Video-Enhancer-2.0-MacOS_x86_64.zip
          path: REAL-Video-Enhancer-2.0-MacOS_x86_64.zip

  Release:
    needs: [build-Windows, build-Linux, build-MacOS]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Generate version and tag
        id: version_tag
        run: |
          version=$(python -c "from datetime import datetime; print(str(datetime.now()).split(' ')[0].replace('-',''))")
          tag=$(python -c "import random, string; print(''.join(random.choices(string.ascii_letters, k=8)))")
          echo "Version=$version"
          echo "Tag=$version"
          echo "::set-output name=version::$version"
          echo "::set-output name=tag::$version"
      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1        
        with:
          name: REAL Video Enhancer 2.0 Pre-Release
          tag_name: prerelease_2.0
          body: ${{ steps.version_tag.outputs.tag }}
          draft: false
          prerelease: true
          
          files: |
              artifacts/REAL-Video-Enhancer-2.0-Windows.zip/REAL-Video-Enhancer-2.0-Windows.zip
              artifacts/REAL-Video-Enhancer-2.0-Linux.zip/REAL-Video-Enhancer-2.0-Linux.zip
              artifacts/REAL-Video-Enhancer-2.0-MacOS_x86_64.zip/REAL-Video-Enhancer-2.0-MacOS_x86_64.zip

              
              
        

     
