
name: build-prerelease

on:
  workflow_dispatch:
  
jobs:
  
  build-Linux:
    runs-on: ubuntu-20.04 
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15
      
      - name: install other requirements
        run : |
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
      - name: Build
        run: python3 build.py --build_exe
      
      - name: compress archive
        run: |
          zip -r REAL-Video-Enhancer-2.1.5-Linux.zip bin/

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: REAL-Video-Enhancer-2.1.5-Linux.zip
          path: REAL-Video-Enhancer-2.1.5-Linux.zip
          
  build-Windows:
    runs-on: windows-2019
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
          
      - name: Build
        run: python3 build.py --build_exe
      
      - name: compress archive
        run: |
            cd dist
            tar -a -c -f REAL-Video-Enhancer-2.1.5-Windows.zip REAL-Video-Enhancer
            cd ..
            cp dist/REAL-Video-Enhancer-2.1.5-Windows.zip REAL-Video-Enhancer-2.1.5-Windows.zip

      - name: Save Archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: REAL-Video-Enhancer-2.1.5-Windows.zip
          path: REAL-Video-Enhancer-2.1.5-Windows.zip

  Release:
    needs: [build-Windows, build-Linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - uses: actions/checkout@v3
      - name: Generate version and tag
        id: version_tag
        run: |
          git clone https://github.com/tntwise/real-video-enhancer
          version=$(python -c "from datetime import datetime; print(str(datetime.now()).split(' ')[0].replace('-',''))")
          tag=$(python -c "import random, string; print(''.join(random.choices(string.ascii_letters, k=8)))")
          body=$(python3 printchangelog.py)
          echo "Version=$version"
          echo "Tag=$version"
          echo "Body=$body"
          echo "::set-output name=version::$version"
          echo "::set-output name=tag::$version"
          echo "::set-output name=body::$body"
      
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1        
        with:
          name: REAL Video Enhancer 2.1.5 Pre-Release
          tag_name: prerelease_2.1.5
          body: ${{ steps.version_tag.outputs.body }}
          draft: false
          prerelease: true
          
          files: |
              artifacts/REAL-Video-Enhancer-2.1.5-Windows.zip/REAL-Video-Enhancer-2.1.5-Windows.zip
              artifacts/REAL-Video-Enhancer-2.1.5-Linux.zip/REAL-Video-Enhancer-2.1.5-Linux.zip

              
              
        

     
